[package]
name = "cs"
version = "0.0.1"
authors = ["Shingo Sato <shinsugar@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
